version: "3.2"

services:
  rabbitmq:
    container_name: 'rabbitmq_compra'
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdatacompra:/var/lib/rabbitmq/
    networks:
      - rabbitmq_compra

  zipkin-server:
    container_name: zipkin_server_compra
    image: openzipkin/zipkin:2.23.2
    expose:
      - '9411'
    ports:
      - '9411:9411'
    networks:
      - zipkin_compra

networks:
  rabbitmq_compra:
    driver: bridge
  zipkin_compra:
    driver: bridge

volumes:
  rabbitmqdatacompra:
